name: PythonCI
on:
  push:
    branches: [ master, coverage-support ]
  pull_request:
    branches: [ master, coverage-support ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [pypy3, 3.5, 3.6, 3.7, 3.8, 3.9, "3.10"]
        exclude:
          # apparently win/mac don't have pypy3
          - os: windows-latest
            python-version: pypy3
          - os: macos-latest
            python-version: pypy3
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pygments>=2.5.2 pytest pytest-cov pytest-html
      - name: Test
        env:
          PYTHONPATH: lib
          OUTDIR: build/qa-${{ matrix.python-version }}-${{ matrix.os }}
        run: |
          py.test \
            --cov=markdown2 \
            --cov-report=html:$OUTDIR/coverage \
            --junitxml=$OUTDIR/junit/junit.xml --html=$OUTDIR/junit/junit.html --self-contained-html \
            -k "not knownfailure" test
      
